main: fr.azrotho.bingo.Main
name: Bingo
version: 1.0
author: Azrotho
description: Bingo plugin for the server
website: https://azrotho.fr
api-version: 1.17
commands:
  debug:
    description: Debug command
    usage: /debug
    aliases: [d]
  bingo:
    description: Bingo command
    usage: /bingo
    aliases: [b]